# Generated by Django 5.1.1 on 2024-10-08 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_archivos_referencia_tipo_id_and_more'),
        ('tareas', '0002_tareas_asignadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermedia_archivos_entregables',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.archivos_referencia')),
                ('asignacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tareas_asignadas')),
                ('info_tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.info_tareas')),
            ],
            options={
                'db_table': 'Intermedia_archivos_entregables',
            },
        ),
        migrations.CreateModel(
            name='Intermedia_tareas_archivos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.archivos_referencia')),
                ('info_tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.info_tareas')),
            ],
            options={
                'db_table': 'Intermedia_tareas_archivos',
            },
        ),
    ]
