# Generated by Django 5.1.1 on 2024-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_intermedia_archivos_entregables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_tareas',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
