# Generated by Django 5.1.1 on 2024-11-04 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_info_tareas_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas_asignadas',
            name='info_tarea_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.info_tareas'),
        ),
    ]
