services:
  frontend:
    container_name: intranet-front
    image: intranet-frontend:v2
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: intranet-back
    image: intranet-backend:v2
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://intranet-admin:fwd2025@postgres:5432/intranet_db
    volumes:
      - ./intranet_backend:/app
    command:
      [
        "./wait-for-it.sh",
        "-t",
        "30",
        "postgres:5432",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=intranet-admin
      - POSTGRES_PASSWORD=fwd2025
      - POSTGRES_DB=intranet_db
    volumes:
      - intranet_postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro

volumes:
  intranet_postgres_data:
