FROM python:3.12.6
WORKDIR /app
COPY ./intranet_backend/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY ./intranet_backend .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
