services:
  frontend:
    container_name: intranet-front-dev
    image: intranet-front-dev:1.1.0
    build:
      context: .
      dockerfile: Dockerfile.frontenddev

    volumes:
      - ./intranet-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  backend:
    container_name: intranet-back-dev
    image: intranet-back-dev:1.1.0
    build:
      context: .
      dockerfile: Dockerfile.backenddev
    ports:
      - "8000:8000"
    volumes:
      - ./intranet_backend:/app
    command:
      [
        "./wait-for-it.sh",
        "-t",
        "30",
        "postgres:5000",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]

    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=intranet_admin
      - POSTGRES_PASSWORD=fwd2025
      - POSTGRES_DB=intranet_db
      - PGPORT=5000
    volumes:
      - intranet_postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro

volumes:
  intranet_postgres_data:
