services:
  - name: intranet-frontend
    type: web
    env: docker
    dockerfilePath: Dockerfile.frontend
    buildCommand: docker build --target production --build-arg NODE_ENV=production -t intranet-frontend:v2 .
    startCommand: docker run -p 80:80 intranet-frontend:v2
    envVars:
      - key: NODE_ENV
        value: production
    dependsOn:
      - intranet-backend

  - name: intranet-backend
    type: web
    env: docker
    dockerfilePath: Dockerfile.backend
    buildCommand: docker build -t intranet-backend:v2 .
    startCommand: >
      python manage.py migrate
    envVars:
      - key: DATABASE_URL
        value: postgresql://intranet_admin:sfcAZgrJ2m6OP1mxJL0cfLsfXoA5rEG7@dpg-cto47jrtq21c73crb0m0-a/intranet_db_slfe
    volumes:
      - path: ./intranet_backend
        mountPath: /app
