services:
  - name: intranet-frontend
    type: web
    env: docker
    dockerfilePath: Dockerfile.frontend
    buildCommand: docker build --target production --build-arg NODE_ENV=production -t intranet-frontend:v2 .
    startCommand: docker run -p 80:80 intranet-frontend:v2
    envVars:
      - key: NODE_ENV
        value: production
    dependsOn:
      - intranet-backend

  - name: intranet-backend
    type: web
    env: docker
    dockerfilePath: Dockerfile.backend
    buildCommand: docker build -t intranet-backend:v2 .
    startCommand: >
      ./wait-for-it.sh -t 30 mysql:3306 -- python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        value: postgresql://intranet_admin:sfcAZgrJ2m6OP1mxJL0cfLsfXoA5rEG7@dpg-cto47jrtq21c73crb0m0-a.oregon-postgres.render.com/intranet_db_slfe  # Use the Render-provided MySQL connection string
    volumes:
      - path: ./intranet_backend
        mountPath: /app
