# Generated by Django 5.1.1 on 2024-09-30 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_archivos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Archivos_referencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=1000)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.tipos_archivos')),
            ],
        ),
    ]
