# Generated by Django 5.1.1 on 2024-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_archivos_referencia_tipo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos_referencia',
            name='key',
            field=models.UUIDField(),
        ),
        migrations.AlterUniqueTogether(
            name='archivos_referencia',
            unique_together={('nombre', 'key')},
        ),
        migrations.AddIndex(
            model_name='archivos_referencia',
            index=models.Index(fields=['key', 'nombre'], name='info-archivo-indx'),
        ),
        migrations.AddIndex(
            model_name='archivos_referencia',
            index=models.Index(fields=['key'], name='key-archivo-indx'),
        ),
        migrations.AddIndex(
            model_name='tipos_archivos',
            index=models.Index(fields=['id'], name='tipos-achivo-id-indx'),
        ),
    ]
