# Generated by Django 5.1.1 on 2024-12-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_delete_tipos_archivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCloudBucketFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'google_cloud_bucket_files',
                'indexes': [models.Index(fields=['id', 'nombre'], name='info-cloud-indx'), models.Index(fields=['nombre'], name='nombre-archivo-indx'), models.Index(fields=['id'], name='id-cloud')],
                'unique_together': {('nombre', 'id')},
            },
        ),
    ]
