# Generated by Django 5.1.4 on 2025-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_googlecloudbucketfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecloudbucketfiles',
            name='expiracion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='googlecloudbucketfiles',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
