# Generated by Django 5.1.4 on 2025-02-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_googlecloudbucketfiles_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecloudbucketfiles',
            name='expiracion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='googlecloudbucketfiles',
            name='url',
            field=models.URLField(),
        ),
    ]
