# Generated by Django 5.1.4 on 2025-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_googlecloudbucketfiles_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecloudbucketfiles',
            name='expiracion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='googlecloudbucketfiles',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
