FROM python:3.12.6
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt --no-cache-dir
# Copiar desde el local
# COPY wait-for-it.sh ./
# Copiar desde el github (wait-for-it)
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*
RUN curl -o ./wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
COPY . .
EXPOSE 8000