# Generated by Django 5.1.1 on 2024-09-27 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('ubicacion', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sede_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.sedes')),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
    ]
