# Generated by Django 5.1.1 on 2024-09-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_sedes_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='nombre_grupo',
            field=models.CharField(default='No defindo', max_length=100),
        ),
    ]
