# Generated by Django 5.1.1 on 2024-09-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_grupos_nombre_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='nombre_grupo',
            field=models.CharField(max_length=100),
        ),
    ]
