# Generated by Django 5.1.1 on 2024-09-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_cursos_table_grupos_cursos_intermedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupos_cursos_intermedia',
        ),
    ]
