# Generated by Django 5.1.1 on 2024-09-28 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_grupos_cursos_intermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='nombre',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='El nombre debe al menos mayor  a 3 caracteres')]),
        ),
    ]
