# Generated by Django 5.1.1 on 2024-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_sedes_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='ubicacion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='sedes',
            unique_together={('nombre', 'ubicacion')},
        ),
        migrations.AddIndex(
            model_name='sedes',
            index=models.Index(fields=['nombre', 'ubicacion'], name='nombre-ubicacion-indx'),
        ),
        migrations.AddIndex(
            model_name='sedes',
            index=models.Index(fields=['id'], name='id-sedes-indx'),
        ),
    ]
