# Generated by Django 5.1.1 on 2024-10-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_sedes_ubicacion_alter_sedes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupos',
            unique_together={('sede_id', 'nombre_grupo')},
        ),
        migrations.AddIndex(
            model_name='grupos',
            index=models.Index(fields=['sede_id', 'nombre_grupo'], name='sede_id-nombre_grupo-indx'),
        ),
        migrations.AddIndex(
            model_name='grupos',
            index=models.Index(fields=['id'], name='id-grupos-indx'),
        ),
    ]
