# Generated by Django 5.1.1 on 2024-10-08 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_grupos_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intengrantes_de_grupo',
            unique_together={('grupo_id', 'usuario_id')},
        ),
        migrations.AddIndex(
            model_name='intengrantes_de_grupo',
            index=models.Index(fields=['usuario_id', 'grupo_id'], name='IntegranteGrupo-IG-indx'),
        ),
        migrations.AddIndex(
            model_name='intengrantes_de_grupo',
            index=models.Index(fields=['usuario_id'], name='usuario_id-IG-indx'),
        ),
        migrations.AddIndex(
            model_name='intengrantes_de_grupo',
            index=models.Index(fields=['grupo_id'], name='grupo_id-IG-indx'),
        ),
        migrations.AddIndex(
            model_name='intengrantes_de_grupo',
            index=models.Index(fields=['id'], name='id-IG-indx'),
        ),
    ]
