# Generated by Django 5.1.1 on 2024-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_intengrantes_de_grupo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursos',
            unique_together={('id', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='cursos',
            index=models.Index(fields=['id'], name='id-cursos-indx'),
        ),
    ]
