# Generated by Django 5.1.4 on 2025-01-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_alter_intengrantes_de_grupo_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='detalles',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
