# Generated by Django 5.1.1 on 2024-09-25 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(default='no_definido', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cedula',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.roles'),
        ),
    ]
