# Generated by Django 5.1.1 on 2024-09-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuarios_options_alter_roles_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='rol_id',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.roles'),
        ),
    ]
