# Generated by Django 5.1.1 on 2024-09-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuarios_cedula_estudiantes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estudiantes',
            table='Estudiantes',
        ),
    ]
