# Generated by Django 5.1.1 on 2024-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_estudiantes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
