# Generated by Django 5.1.1 on 2024-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuarios_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
