# Generated by Django 5.1.1 on 2024-09-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_roles_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(default='no_definido', max_length=500),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default='no_definido', max_length=200),
        ),
    ]
