# Generated by Django 5.1.1 on 2024-09-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_usuarios_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
