# Generated by Django 5.1.1 on 2024-09-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_estudiantes_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(default='no definido', max_length=254, unique=True),
        ),
    ]
