# Generated by Django 5.1.1 on 2024-10-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_usuarios_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.roles'),
        ),
    ]
