# Generated by Django 5.1.1 on 2024-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_usuarios_cedula_nombre_apellidos_indx'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['email'], name='email-indx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['id', 'email'], name='email-id-indx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['id', 'first_name'], name='nombre-id-indx'),
        ),
    ]
