# Generated by Django 5.1.1 on 2024-10-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_estudiantes_usuario_id'),
        ('api', '0021_alter_estudiantes_unique_together_and_more'),
    ]

    operations = [
    ]
