# Generated by Django 5.1.1 on 2024-10-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20241009_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
