# Generated by Django 5.1.4 on 2025-01-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usuarios_is_socioemocional'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo_cedula',
            field=models.CharField(choices=[('pasaporte', 'PASAPORTE'), ('nacional', 'NACIONAL'), ('extranjero', 'EXTRANJERO')], default='nacional', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['tipo_cedula'], name='tipo-cedula-indx'),
        ),
    ]
