# Generated by Django 5.1.4 on 2025-01-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_usuarios_tipo_cedula_alter_usuarios_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
