# Generated by Django 5.1.4 on 2025-02-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_usuarios_cedula'),
        ('files', '0007_googlecloudbucketfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='perfilUrl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.googlecloudbucketfiles'),
        ),
    ]
