# Generated by Django 5.1.4 on 2025-01-10 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0026_alter_usuarios_cedula'),
        ('cursos', '0017_alter_intengrantes_de_grupo_usuario_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dia_asistencia', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ausente', 'AUSENTE'), ('presente', 'PRESENTE'), ('tardia', 'TARDIA')], default='ausente', max_length=8)),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiantes')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.grupos')),
                ('responsable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistencias',
                'indexes': [models.Index(fields=['grupo_id'], name='grupo-AS-indx'), models.Index(fields=['dia_asistencia'], name='name-AS-indx'), models.Index(fields=['estudiante_id'], name='estudiante-AS-indx')],
            },
        ),
    ]
