# Generated by Django 5.1.4 on 2025-01-11 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencias',
            name='responsable_id',
        ),
        migrations.CreateModel(
            name='ReporteDeAsistencias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asistencias',
            name='reporte_asistencias_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias.reportedeasistencias'),
        ),
    ]
