# Generated by Django 5.1.4 on 2025-01-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_remove_asistencias_responsable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='reporte_asistencias_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asistencias.reportedeasistencias'),
            preserve_default=False,
        ),
    ]
