# Generated by Django 5.1.4 on 2025-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_alter_asistencias_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='estado',
            field=models.CharField(choices=[('ausente', 'AUSENTE'), ('presente', 'PRESENTE'), ('tardia', 'TARDIA'), ('retiro', 'RETIRO')], default='presente', max_length=8),
        ),
    ]
