# Generated by Django 5.1.1 on 2024-10-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes_info',
            name='estado',
            field=models.CharField(choices=[('denegado', 'DENEGADO'), ('aprobado', 'APROBADO'), ('en espera', 'EN ESPERA')], default='EN ESPERA', max_length=9),
        ),
        migrations.AlterField(
            model_name='reportes_info',
            name='tipo_incidente',
            field=models.CharField(choices=[('tardia', 'TARDIA'), ('retiro', 'RETIRO'), ('ausencia', 'AUSENCIA')], default='TARDIA', max_length=8),
        ),
    ]
