# Generated by Django 5.1.1 on 2024-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_rename_usuario_reporte_usuario_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes_info',
            name='tipo_incidente',
            field=models.CharField(choices=[('tardia', 'TARDIA'), ('retiro', 'RETIRO'), ('ausencia', 'AUSENCIA'), ('permiso especial', 'PERMISO ESPECIAL')], default='TARDIA', max_length=17),
        ),
    ]
