# Generated by Django 5.1.1 on 2024-10-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_archivos_referencia_id_archivo'),
        ('reportes', '0006_alter_reportes_info_dia_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes_info',
            name='archivo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.archivos_referencia'),
        ),
    ]
