# Generated by Django 5.1.1 on 2024-10-30 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20241009_1617'),
        ('cursos', '0017_alter_intengrantes_de_grupo_usuario_id'),
        ('files', '0005_archivos_referencia_id_archivo'),
        ('reportes', '0007_reportes_info_archivo_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportes_info',
            index=models.Index(fields=['archivo_id'], name='archivo_report_indx'),
        ),
    ]
