# Generated by Django 5.1.1 on 2024-10-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_reportes_info_archivo_report_indx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes_info',
            name='estado',
            field=models.CharField(choices=[('denegado', 'DENEGADO'), ('aprobado', 'APROBADO'), ('en espera', 'EN ESPERA')], default='en espera', max_length=9),
        ),
        migrations.AlterField(
            model_name='reportes_info',
            name='tipo_incidente',
            field=models.CharField(choices=[('tardia', 'TARDIA'), ('retiro', 'RETIRO'), ('ausencia', 'AUSENCIA'), ('permiso especial', 'PERMISO ESPECIAL')], default='tardia', max_length=17),
        ),
    ]
