# Generated by Django 5.1.4 on 2025-01-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_alter_reportes_info_estado_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportes_info',
            name='archivo_report_indx',
        ),
        migrations.RemoveField(
            model_name='reportes_info',
            name='archivo_id',
        ),
    ]
