# Generated by Django 5.1.4 on 2025-01-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usuarios_is_socioemocional'),
        ('cursos', '0017_alter_intengrantes_de_grupo_usuario_id'),
        ('files', '0007_googlecloudbucketfiles'),
        ('reportes', '0010_remove_reportes_info_archivo_report_indx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes_info',
            name='archivo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.googlecloudbucketfiles'),
        ),
        migrations.AddIndex(
            model_name='reportes_info',
            index=models.Index(fields=['archivo_id'], name='archivo_report_indx'),
        ),
    ]
