# Generated by Django 5.1.4 on 2025-02-11 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_usuarios_perfilurl'),
        ('cursos', '0018_cursos_detalles'),
        ('files', '0007_googlecloudbucketfiles'),
        ('reportes', '0011_reportes_info_archivo_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes_info',
            name='descripcion_comprobante',
            field=models.CharField(default='Sin descripcion', max_length=300),
        ),
        migrations.AddField(
            model_name='reportes_info',
            name='presento_aviso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='reportes_info',
            index=models.Index(fields=['presento_aviso'], name='presento_aviso_indx'),
        ),
    ]
