# Generated by Django 5.1.1 on 2024-10-02 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0002_alter_contenidos_table'),
        ('files', '0002_alter_archivos_referencia_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContenidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('archivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.archivos_referencia')),
            ],
        ),
    ]
