# Generated by Django 5.1.1 on 2024-10-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0003_subcontenidos'),
        ('files', '0002_alter_archivos_referencia_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontenidos',
            name='archivo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.archivos_referencia'),
        ),
    ]
