# Generated by Django 5.1.1 on 2024-10-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0004_alter_subcontenidos_archivo_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcontenidos',
            table='subcontenidos',
        ),
    ]
