# Generated by Django 5.1.1 on 2024-10-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0005_alter_subcontenidos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontenidos',
            name='contenido_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos_contenidos.contenidos'),
        ),
    ]
