# Generated by Django 5.1.1 on 2024-10-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0007_rename_contenido_id_subcontenidos_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontenidos',
            old_name='contenido',
            new_name='contenido_id',
        ),
    ]
