# Generated by Django 5.1.1 on 2024-10-06 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0009_rename_curso_id_contenidos_curso_and_more'),
        ('files', '0003_remove_archivos_referencia_tipo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontenidos',
            name='archivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.archivos_referencia'),
        ),
    ]
