# Generated by Django 5.1.1 on 2024-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_grupos_cursos_intermedia_unique_together_and_more'),
        ('cursos_contenidos', '0010_alter_subcontenidos_archivo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contenidos',
            index=models.Index(fields=['id', 'nombre'], name='contenidos-indx'),
        ),
        migrations.AddIndex(
            model_name='contenidos',
            index=models.Index(fields=['id'], name='id-contenidos-indx'),
        ),
    ]
