# Generated by Django 5.1.1 on 2024-10-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0011_contenidos_contenidos_indx_and_more'),
        ('files', '0003_remove_archivos_referencia_tipo_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subcontenidos',
            index=models.Index(fields=['contenido'], name='subcont-contenido-indx'),
        ),
        migrations.AddIndex(
            model_name='subcontenidos',
            index=models.Index(fields=['archivo'], name='subcont-archivo-indx'),
        ),
        migrations.AddIndex(
            model_name='subcontenidos',
            index=models.Index(fields=['id'], name='id-subcont-indx'),
        ),
    ]
