# Generated by Django 5.1.4 on 2024-12-28 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0016_comunicados_user_comunicado_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subcontenidos',
            name='subcont-archivo-indx',
        ),
        migrations.RemoveField(
            model_name='subcontenidos',
            name='archivo',
        ),
        migrations.AddField(
            model_name='contenidos',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenidos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenidos',
            name='fecha_de_desbloqueo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subcontenidos',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcontenidos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
