# Generated by Django 5.1.1 on 2024-12-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0016_comunicados_user_comunicado_and_more'),
        ('files', '0007_googlecloudbucketfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontenidos',
            name='archivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.googlecloudbucketfiles'),
        ),
    ]
