# Generated by Django 5.1.4 on 2024-12-28 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0017_remove_subcontenidos_subcont_archivo_indx_and_more'),
        ('files', '0007_googlecloudbucketfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontenidos',
            name='archivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.googlecloudbucketfiles'),
        ),
    ]
