# Generated by Django 5.1.1 on 2024-12-22 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0018_contenidos_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontenidos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
