# Generated by Django 5.1.1 on 2024-12-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0019_subcontenidos_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenidos',
            name='fecha_de_desbloqueo',
            field=models.DateField(null=True),
        ),
    ]
