# Generated by Django 5.1.1 on 2024-12-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_contenidos', '0020_contenidos_bloqueado_contenidos_fecha_de_desbloqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontenidos',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
